Repository ta-oliver/infertrade, pull requests merged in 2021-08, with the labels that each got.

#178 Updated unit test coverage
  .coveragerc
  infertrade/algos/community/allocations.py
  infertrade/base.py
  infertrade/utilities/performance.py
  requirements.txt
  tests/LBMA_Gold.csv
  tests/test_PandasEnum.py
  tests/test_allocations.py
  tests/test_api.py
  tests/test_base.py
  tests/test_operations.py
  tests/test_performance.py
  tests/test_simple_functions.py
Labels: Ready for Review

#182 Documentation - True Strength Index
  docs/strategies/pdf/TrueStrengthIndex.pdf
  docs/strategies/tex/TrueStrengthIndex.tex
  infertrade/utilities/operations.py
Labels: documentation

#181 Documentation - Triple Exponential Average
  docs/strategies/pdf/TripleExponentialAverage.pdf
  docs/strategies/tex/TripleExponentialAverage.tex
  infertrade/utilities/operations.py
Labels: documentation

#175 Documentation - Percentage Price Oscillator
  docs/strategies/pdf/PercentagePriceOscillator.pdf
  docs/strategies/tex/PercentagePriceOscillator.tex
Labels: documentation

#173 Documentation for AROON Indicator
  docs/strategies/pdf/Aroon.pdf
  docs/strategies/tex/Aroon.tex
Labels: documentation

#191 Update Strategy Description
  docs/strategies/pdf/Aroon.pdf
  docs/strategies/pdf/DetrendedPriceOscillator.pdf
  docs/strategies/pdf/ExponentialMovingAverage.pdf
  docs/strategies/pdf/MovingAverageConvergenceDivergence.pdf
  docs/strategies/pdf/PercentagePriceOscillator.pdf
  docs/strategies/pdf/RelativeStrengthIndex.pdf
  docs/strategies/tex/Aroon.tex
  docs/strategies/tex/DetrendedPriceOscillator.tex
  docs/strategies/tex/ExponentialMovingAverage.tex
  docs/strategies/tex/MovingAverageConvergenceDivergence.tex
  docs/strategies/tex/PercentagePriceOscillator.tex
  docs/strategies/tex/RelativeStrengthIndex.tex
Labels: documentation, Changes requested

#192 Documentation - Bollinger Bands
  docs/strategies/pdf/BollingerBand.pdf
  docs/strategies/tex/BollingerBand.tex
Labels: documentation

#203 Documentation - Rate of Change
  docs/strategies/pdf/RateOfChange.pdf
  docs/strategies/tex/RateOfChange.tex
Labels: documentation

#207 Documentation - Percentage Volume Oscillator(PVO)
  docs/strategies/pdf/PercentageVolumeOscillator.pdf
  docs/strategies/tex/PercentageVolumeOscillator.tex
Labels: documentation

#209 Documentation - Stochastic RSI (StochRSI)
  docs/strategies/pdf/StochasticRelativeStrengthIndex.pdf
  docs/strategies/tex/StochasticRelativeStrengthIndex.tex
Labels: documentation

#208 Documentation - Average Directional Movement Index (ADX)
  docs/strategies/pdf/AverageDirectionalMovementIndex.pdf
  docs/strategies/tex/AverageDirectionalIndex.tex
Labels: documentation

#215 Documentation - Schaff Trend Cycle (STC)
  docs/strategies/pdf/SchaffTrendCycle.pdf
  docs/strategies/tex/SchaffTrendCycle.tex
Labels: documentation

#210 Documentation - Simple Moving Average (SMA)
  docs/strategies/pdf/SimpleMovingAverage.pdf
  docs/strategies/tex/SimpleMovingAverage.tex
Labels: documentation
