Repository ta-oliver/infertrade, pull requests merged in 2021-07, with the labels that each got.

#116 Adds Golden/Death Cross rule and additional unit tests for calculation_allocations_from_cash
  examples/BTC.csv
  infertrade/algos/community/allocations.py
  tests/test_performance.py
Labels: Changes requested, in progress

#139 Restrict decorator
  infertrade/algos/community/signals.py
  infertrade/utilities/operations.py
  infertrade/utilities/performance.py
  tests/test_decorators.py
Labels: Changes requested, in progress

#142 Adding logo to images required to build the pdf from tex
  docs/strategies/images/Allocation_MarketSeries_360_380.pdf
  docs/strategies/images/Allocation_ResearchValue_360_380.pdf
  docs/strategies/images/Market_ResearchSeries_360_380.pdf
  docs/strategies/images/Market_ResearchValue_360_380.pdf
  docs/strategies/images/StrategyReturn_MarketSeries_360_380.pdf
  docs/strategies/images/logo.png
  docs/strategies/pdf/LevelRegression.pdf
  docs/strategies/pdf/LevelRelationship.pdf
  docs/strategies/pdf/PriceTrendOrReversionRelationship.pdf
  docs/strategies/pdf/ProportionalWeighting.pdf
  docs/strategies/pdf/RollingChangeRegression.pdf
  docs/strategies/pdf/RollingCombinationRegression.pdf
  docs/strategies/pdf/RollingCombinationRegression6m.pdf
  docs/strategies/pdf/RollingDifferenceRegression.pdf
  docs/strategies/pdf/RollingDifferenceRegression6m.pdf
  docs/strategies/pdf/RollingLevelRegression.pdf
  docs/strategies/pdf/RollingLevelRegression6m.pdf
  docs/strategies/pdf/RollingLogDifferenceRegression.pdf
  docs/strategies/pdf/RollingLogDifferenceRegression6m.pdf
  docs/strategies/pdf/RollingPriceChangeRegression.pdf
  docs/strategies/pdf/RollingPriceCombinationRegression.pdf
  docs/strategies/pdf/RollingPriceLevelRegression.pdf
  docs/strategies/pdf/StaticChangeRegression.pdf
  docs/strategies/pdf/StaticCombinationRegression.pdf
  docs/strategies/pdf/StaticDifferenceRegression.pdf
  docs/strategies/pdf/StaticLevelRegression.pdf
  docs/strategies/pdf/StaticLogDifferenceRegression.pdf
  docs/strategies/pdf/WeightedMovingAverages.pdf
  docs/strategies/pdf/ZScoredAndChangeRegression.pdf
  docs/strategies/pdf/ZScoredRegression.pdf
  docs/strategies/tex/ChangeRelationship.tex
  docs/strategies/tex/CombinationRelationship.tex
  docs/strategies/tex/DifferenceRelationship.tex
  docs/strategies/tex/LevelRelationship.tex
  docs/strategies/tex/LogDifferenceRegression.tex
  docs/strategies/tex/PriceTrendOrReversionRelationship.tex
  docs/strategies/tex/ProportionalWeighting.tex
  docs/strategies/tex/RollingCombinationRegression6m.tex
  docs/strategies/tex/RollingDifferenceRegression.tex
  docs/strategies/tex/RollingDifferenceRegression6m.tex
  docs/strategies/tex/RollingLevelRegression6m.tex
  docs/strategies/tex/RollingLogDifferenceRegression.tex
  docs/strategies/tex/RollingLogDifferenceRegression6m.tex
  docs/strategies/tex/RollingPriceLevelRegression.tex
  docs/strategies/tex/SimpleMovingAverage.tex
  docs/strategies/tex/StaticChangeRegression.tex
  docs/strategies/tex/StaticLevelRegression.tex
  docs/strategies/tex/WeightedMovingAverages.tex
  docs/strategies/tex/ZScoredAndChangeRegression.tex
  docs/strategies/tex/ZScoredRegression.tex
  docs/strategies/tex/common_symbols_and_format.tex
Labels: Changes requested, documentation

#158 Relative Strength Index Documentation
  docs/strategies/pdf/RelativeStrengthIndex.pdf
  docs/strategies/tex/RelativeStrengthIndex.tex
Labels: documentation

#154 Strategy Documentation - Exponential Moving Average
  docs/strategies/pdf/ExponentialMovingAverage.pdf
  docs/strategies/tex/ExponentialMovingAverage.tex
Labels: Changes requested, documentation

#166 Documentation for Moving Average Convergence Divergence
  docs/strategies/pdf/MovingAverageConvergenceDivergence.pdf
  docs/strategies/tex/MovingAverageConvergenceDivergence.tex
Labels: documentation

#174 Documentation - Detrended Price Oscillator
  docs/strategies/pdf/DetrendedPriceOscillator.pdf
  docs/strategies/tex/DetrendedPriceOscillator.tex
  docs/strategies/tex/common_symbols_and_format.tex
Labels: documentation
